### ISSUE TITLE
Practical Example 3 needs more information

### ISSUE THREAD

**Issue by tott** [otavioschwanck/cool-substitute.nvim#11]
Love the plugin but could not quite figure out how to reproduce [Practical example 3](https://github.com/otavioschwanck/cool-substitute.nvim/tree/main#practical-example-3)

Could you let me know how to mark something that's not a word ie. when trying to replace something like `    => '` with `    => "`
I know a stupid example but you get the gist.

**Comment by otavioschwanck** [comment]
to do that, just go to visual mode with `v` select the characters and press gm
