### ISSUE TITLE
minimal docs

### ISSUE THREAD

**Issue by matu3ba** [otavioschwanck/cool-substitute.nvim#5]
It would be nice to have a minimal help page for all settings + commands, because the README is not very nice to search through from neovim (say on updates).

Other observations:
1.
One example is mentioning `using U to uppercase stuff`, but I dont see `U` being bound to what looks like `~`.
See also `:h U`:
```txt
Undo all latest changes on one line, the line where
the latest change was made. |U| itself also counts as
a change, and thus |U| undoes a previous |U|.
```
2.
Typofix of README:
`:s/Pros of cool-substitute:/Pros/g`

**Comment by otavioschwanck** [comment]
1. U on visual mode.
1.1. I will add some better examples later, i am getting a better list of usages in my daily usage.
2. I will fix.

About the help, i want to do, but i don't have time right now, probably in this weekend i create something

**Comment by otavioschwanck** [comment]
Done
