### ISSUE TITLE
wiki/docs: lua functions to read/write register from/to file

### ISSUE THREAD

**Issue by matu3ba** [otavioschwanck/cool-substitute.nvim#6]
I like the plugin so far! I hope it remains relative simple until macros can be debugged. :)

It would be nice to have some guide on how to write registers and recommendation to save + restore macros.
I believe on reddit you told me that you store the macro escaped somewhere, but I might be wrong.
Exposing the function to the user with simple guide sounds like a nice to have thing.

This is probably more of an edge use case, but just having the option to save things sounds nice.

**Comment by otavioschwanck** [comment]
The macro is saved on register "o" by default, you can access with:
:reg o

the register is overwrite when capturing another macro.  The purpose of the plugin is to be a quick macro for substitute / do some extra stuff. 

What we can do in the future is  a command to save last macro, it will ask a name, and after while, you can type :ReloadMacro macroname, and it will be reloaded to reg o.  Then, will be asked a search term, you enter one, then keep pressing M to run the macro on the search terms. What you think?

**Comment by matu3ba** [comment]
Sounds good, but optionally skipping interactivity would be nice if possible.

**Comment by otavioschwanck** [comment]
> Sounds good, but optionally skipping interactivity would be nice if possible.

what you think:

Command to rerun last macro:  select word / use visual selected, just apply the macro when needed.  Easy to do it.

And later, we can see a way to save

**Comment by matu3ba** [comment]
sounds good.

**Comment by otavioschwanck** [comment]
i've created the function to rerun last macro. `g!r` the default keybinding.

About saving, ill keep on the roadmap
